### PR TITLE
Sharing Feature Completed and running

### PR DESCRIPTION
**Pull request by lepatrick714**
This PR is to integrate the sharing feature to master. I recommend just testing out the branch to make sure it's stable prior to accepting this PR.

As always, let me know if you have any questions/concerns.

### CODE REVIEW

**Comment by RBoshae** [comment]
@lepatrick714 should I be able to login -> create board, logout, login again and see the board I created?

What tests should I try?

**Comment by lepatrick714** [comment]
@RBoshae I would do the following with firebase's database on the side

1. Register two new accounts
2. Create one board from one of those accounts
3. Click the share button of said board 
4. Type in the user to be shared's email address 
5. Observe correct changes on firebase

**Comment by RBoshae** [comment]
cool, I'll check it out.

**Comment by Kuzame** [comment]
I just tested the sharing with Jeremy, and we think that it's still buggy. Easy way to test is: 
1. share the board with other user
2. Then try to delete that board
Will provide more details later

Edit*: I suspect because we call the share function in BoardTile class (instead of calling that function in the Dashboard). Check how the formatting for onUnlink and onDelete works.

**Pull request merged**
